[package]
name = "datafusion-geo"
version = "0.1.0"
edition = "2021"

[features]
geos = ["dep:geos"]

[dependencies]
arrow = "50"
datafusion = "36"
tokio = "1.36"
geo = "0.28"
geos = { version = "8.3", features = ["v3_10_0", "geo"], optional = true }